### ISSUE TITLE
Cannot initialize a parameter of type  API_AVAILABLE(ios(10.0))...

### ISSUE THREAD

**Issue by alexborton** [blueshift-labs/Blueshift-iOS-SDK#254]
Adding the iOS SDK to a new React Native 0.70 build is throwing up two errors that seems to be related in xcode during build;

```
// AppDelegate.mm
...
// Set userNotificationDelegate for push notifications
  [config setUserNotificationDelegate:self];

^^ Cannot initialize a parameter of type 'API_AVAILABLE(ios(10.0)) NSObject<UNUserNotificationCenterDelegate> *' with an lvalue of type 'AppDelegate *const __strong'


...

- (void)application:(UIApplication *)application didReceiveLocalNotification:(nonnull UILocalNotification *)notification {
    [[BlueShift sharedInstance].appDelegate application:application handleLocalNotification:notification];
}

^^ Cannot initialize a parameter of type 'UNNotificationRequest * _Nonnull' with an lvalue of type 'UILocalNotification * _Nonnull __strong'
```

I have added the SDK as per the documentation and this was previously working with RN version 0.64. I can't see where this would have changed and the error messaging is a little obscure - hoping you might be able to shed some light.

I have tried this with both `2.2.6` and `2.3.0` and get the same errors in xcode

**Comment by ketanshikharebsft** [comment]
@alexborton Thanks for reaching out, we will review the issue.

**Comment by ketanshikharebsft** [comment]
@alexborton Could you please confirm you have Implemented the `UNUserNotificationCenterDelegate` protocol on `AppDelegate` class in the `AppDelegate.h` file? You can refer to [this](https://developer.blueshift.com/docs/integrate-your-ios-app#setup-appdelegateh) code snippet for reference. Adding this should resolve the #1 issue.

For #2, you can skip adding the `application: didReceiveLocalNotification` method, SDK no more uses it. 

If the issue persists, please raise a support ticket by sending an email to support@getblueshift.com.
