### ISSUE TITLE
Blueshift SDK fails to compile when xcode 14.3 is used

### ISSUE THREAD

**Issue by tomoakley** [blueshift-labs/Blueshift-iOS-SDK#255]
When building an iOS app, with the Blueshift SDK integrated, using Xcode 14.3 the app fails to build with this error:
```
▸ Compiling InAppNotificationEntity.m

❌  /Users/distiller/project/ios/Pods/BlueShift-iOS-SDK/BlueShift-iOS-SDK/InApps/InAppNotificationEntity.m:100:1: non-void function does not return a value [-Werror,-Wreturn-type]

}
                              ^


▸ Compiling HttpRequestOperationEntity.m

❌  /Users/distiller/project/ios/Pods/BlueShift-iOS-SDK/BlueShift-iOS-SDK/HttpRequestOperationEntity.m:137:1: non-void function does not return a value [-Werror,-Wreturn-type]

}
^



❌  /Users/distiller/project/ios/Pods/BlueShift-iOS-SDK/BlueShift-iOS-SDK/HttpRequestOperationEntity.m:192:1: non-void function does not return a value [-Werror,-Wreturn-type]

}
^
```

(output via Circle CI / fastlane job)

Info:
Blueshift SDK: 2.3.0
CircleCI image: [14.3.0 RC](https://circle-macos-docs.s3.amazonaws.com/image-manifest/v11578/manifest.txt), macOS intel machine. We have also experienced this issue while building on local dev M1 machines with Xcode 14.3.0.

**Comment by filiptdz** [comment]
Same issue here

**Comment by filiptdz** [comment]
As a temporary workaround (at least for local builds, but could probably make a build step to make it work on CI too), can modify the pod files to include a `return nil;` as the last statement of the functions that are causing the crash. For example:
```objc
+ (void *)fetchBatchWiseRecordFromCoreDataWithCompletetionHandler:(void (^)(BOOL, NSArray *))handler {
  // function implementation...
  return nil;
}
```

**Comment by ketanshikharebsft** [comment]
Thanks for reaching out @filiptdz @tomoakley. We are already working on a hotfix for this issue, and it is planned to go out by end of this week. We will update here once the hotfix is out.

**Comment by ketanshikharebsft** [comment]
@filiptdz @tomoakley We have released hotfix [v2.3.1](https://github.com/blueshift-labs/Blueshift-iOS-SDK/releases/tag/2.3.1) for this issue.

**Comment by stormgain-dev** [comment]
Hi, @ketanshikharebsft 
Could this patch also be ported to the [Blueshift Cordova Plugin](https://github.com/blueshift-labs/Blueshift-Cordova-Plugin) please?

**Comment by ketanshikharebsft** [comment]
Hi @stormgain-dev, the fix for the Cordova plugin is in progress. I will update here once it's out.

**Comment by ketanshikharebsft** [comment]
@stormgain-dev The Cordova plugin fix is out, you can update to plugin version [v0.1.0](https://github.com/blueshift-labs/Blueshift-Cordova-Plugin/releases/tag/0.1.0).

Closing the ticket as this issue is resolved.
