### ISSUE TITLE
MOM file not found!

### ISSUE THREAD

**Issue by priore** [blueshift-labs/Blueshift-iOS-SDK#262]
Xcode 15.0:

`error: Resource "/Users/..../Library/Developer/Xcode/DerivedData/.....-eqblrtjsknetarallbkprdqzkcfu/Build/Products/Debug-iphonesimulator/BlueShift-iOS-SDK/BlueShift_iOS_SDK.framework/BlueShiftSDKDataModel 2.mom" not found. Run 'pod install' to update the copy resources script.`

I have tried **'pod deintegrate'** and **'pod install'** but still gives the same error.

Please help, thanks.

**Comment by ketanshikharebsft** [comment]
@priore Please update the SDK to the latest SDK version and try. If the issue persists, please reach out to support@getblueshift.com with details so that we can help you further.

**Comment by priore** [comment]
Additional Information :

I use he last version of your SDK v.2.4.1 in a Swift 5 project.

in the Pods-Corriere STG-resources.sh, which is automatically generated by pod install or update by pod update,  includes these six lines:

 ```
 install_resource "${BUILT_PRODUCTS_DIR}/BlueShift-iOS-SDK/BlueShift_iOS_SDK.framework/BlueshiftInboxTableViewCell.nib"
 install_resource "${BUILT_PRODUCTS_DIR}/BlueShift-iOS-SDK/BlueShift_iOS_SDK.framework/BlueShiftSDKDataModel.momd"
 install_resource "${BUILT_PRODUCTS_DIR}/BlueShift-iOS-SDK/BlueShift_iOS_SDK.framework/BlueShiftSDKDataModel 2.mom"
 install_resource "${BUILT_PRODUCTS_DIR}/BlueShift-iOS-SDK/BlueShift_iOS_SDK.framework/BlueShiftSDKDataModel 3.mom"
 install_resource "${BUILT_PRODUCTS_DIR}/BlueShift-iOS-SDK/BlueShift_iOS_SDK.framework/BlueShiftSDKDataModel 4.mom"
 install_resource "${BUILT_PRODUCTS_DIR}/BlueShift-iOS-SDK/BlueShift_iOS_SDK.framework/BlueShiftSDKDataModel.mom"
```
 
when I comment (#) the last four lines (.mom files) the compilation is completed right.

I wrote in support email.
