### ISSUE TITLE
Afnetworking dependency in cocoa pods that gets installed is 3.x but 2.5.4 is used in code 

### ISSUE THREAD

**Issue by rahuljain01** [blueshift-labs/Blueshift-iOS-SDK#29]
AFHTTPRequestOperationManager.h not found issue

**Comment by aswani521** [comment]
Hey @rahuljain01,  right now our pod doesn’t have any dependency with other pods(eg:Afnetworking), we have removed these dependencies in the version of our sdk (0.0.1). 

Let us know if you have more questions
