### ISSUE TITLE
Can not archive when using Blueshift SDk 2.0.1

### ISSUE THREAD

**Issue by ducnnguyen** [blueshift-labs/Blueshift-iOS-SDK#92]
Our podfile using both `BlueShift-iOS-SDK` and `BlueShift-iOS-Extension-SDK`
>pod 'BlueShift-iOS-SDK', '2.0.1'
pod 'BlueShift-iOS-Extension-SDK','2.0.1'

I have error when archive our project
error: Multiple commands produce '/Users/jenkins/Library/Developer/Xcode/DerivedData/TikiProject-ebwsrhyvxixzkzfnutlowxgmsllf/Build/Intermediates.noindex/ArchiveIntermediates/TikiDev/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/BlueShiftBundle.bundle'

**Comment by ducnnguyen** [comment]
Add screenshot
<img width="1377" alt="Screen Shot 2019-11-21 at 3 31 29 PM" src="https://user-images.githubusercontent.com/17038240/69320633-1cf85d80-0c74-11ea-831c-31aea91114dd.png">

>
Showing All Errors Only
Multiple commands produce '/Users/ducnguyen/Library/Developer/Xcode/DerivedData/TikiProject-gcpcfyycdpsiahfnwegzoawmmock/Build/Intermediates.noindex/ArchiveIntermediates/TikiProject/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/BlueShiftBundle.bundle':
1) Target 'BlueShift-iOS-Extension-SDK-BlueShiftBundle' has create directory command with output '/Users/ducnguyen/Library/Developer/Xcode/DerivedData/TikiProject-gcpcfyycdpsiahfnwegzoawmmock/Build/Intermediates.noindex/ArchiveIntermediates/TikiProject/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/BlueShiftBundle.bundle'
2) Target 'BlueShift-iOS-SDK-BlueShiftBundle' has create directory command with output '/Users/ducnguyen/Library/Developer/Xcode/DerivedData/TikiProject-gcpcfyycdpsiahfnwegzoawmmock/Build/Intermediates.noindex/ArchiveIntermediates/TikiProject/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/BlueShiftBundle.bundle'

**Comment by rahulrvp** [comment]
Thanks for reporting.
Please send us an email at support@blueshift.com with the details. We will look into this.

**Comment by ducnnguyen** [comment]
Dear @rahulrvp i uploaded screenshot here. No need email anymore. Please take a look.
Thank you.

**Comment by rahulrvp** [comment]
Dear @ducnnguyen our engineers are looking into this issue.
We would be able to provide you better and fast assistance if we have a support ticket raised from your end as our primary channel for tracking issues is our customer support channel.
If you provide us with your work email address, we can create the tickets for you.

**Comment by ducnnguyen** [comment]
Dear @rahulrvp, i don't have free time to setup any call. I created a pull request for you here to fix all issues which i reported https://github.com/blueshift-labs/Blueshift-iOS-SDK/pull/96
Please take a look. Thank in advance.

**Comment by rahulrvp** [comment]
Dear @ducnnguyen Thanks for the PR. We are trying to understand and solve the issue for you. The iOS engineers suspect this as an integration issue. It would be great if we could get on a short call and close these things faster.

**Comment by rahulrvp** [comment]
Dear @ducnnguyen, did you get a chance to compare the integration steps using the [iOS sample app](https://github.com/blueshift-labs/Blueshift-iOS-SampleApp/tree/development_mainline)? Reach out to us if you still need help.

**Comment by ducnnguyen** [comment]
Dear @rahulrvp, you should remove this line
>s.resource_bundle = { :BlueShiftBundle => 'BlueShift-iOS-SDK/**/*.{xcdatamodeld,xcdatamodel,otf}' }

from `BlueShift-iOS-Extension-SDK.podspec`file

I think xcdatamodel files just needs to be integrated to BlueShift-iOS-SDK

**Comment by Noufalsubair** [comment]
Can you try  the following step  
1. Go to the corresponding path  /Users/{username}/Library/Developer/Xcode/DerivedData
2. clear folder in the path

try & let us know whether is working for you.

**Comment by rahulrvp** [comment]
dear @ducnnguyen did cleaning up the `~/Library/Developer/Xcode/DerivedData` directory and rebuilding the project resolve the issue?

**Comment by ducnnguyen** [comment]
Dear @rahulrvp Clean or clear Derived data not work for me.
<img width="206" alt="Screen Shot 2019-11-29 at 10 28 47 AM" src="https://user-images.githubusercontent.com/17038240/69841742-0913b380-1293-11ea-93e6-dba45fc4a2cc.png">
Build in debug mode is ok but archived to .ipa is fail. All i want is remove this line 
>s.resource_bundle = { :BlueShiftBundle => 'BlueShift-iOS-SDK/**/*.{xcdatamodeld,xcdatamodel,otf}' }

from `BlueShift-iOS-Extension-SDK.podspec`file

**Comment by rahulrvp** [comment]
Got it!
Just to be clear, could you please confirm if this issue is present in **v2.0.3** release or not?

**Comment by ducnnguyen** [comment]
@rahulrvp this issue still happen in `v2.0.3`

**Comment by rahulrvp** [comment]
@ducnnguyen thanks for confirming!

To debug this further we may need to get on a call. We just need to go through the integration steps by doing a screen share and make sure everything is good.

The problem here is that this issue isn’t happening to any other users. So it is a bit of a challenge to remove that line according to our ios dev team.

You can connect with me via email (rahul.raveendran@blueshift.com) to schedule the call. Let us know if that works for you.

**Comment by ducnnguyen** [comment]
@rahulrvp i've just clone your sample app and checkout the branch `development_mainline`
This issue still happen on your sample app.
<img width="1635" alt="Screen Shot 2019-11-29 at 11 32 10 AM" src="https://user-images.githubusercontent.com/17038240/69843866-e508a000-129b-11ea-91ed-ad14f11eeece.png">
My environment is 
>Xcode 10.3
Cocoapod 1.8.4

Did you try to archive your project? Build debug is ok but cannot archive ipa file to upload to AppStore

**Comment by rahulrvp** [comment]
@ducnnguyen Cool. this info helps. Thanks a bunch!
We do archive the project for internal releases, and we never faced the issue with the sample app.
Let's review our dev environment and get back to you.

**Comment by rahulrvp** [comment]
@ducnnguyen we could reproduce this issue at our end with the help of the details you provided in the last comment. We are reviewing the changes now. I will keep you posted once we have an update. Thanks for the help.

**Comment by rahulrvp** [comment]
@ducnnguyen This is a building system related bug. We have the fix ready for this issue. We'll let you know once we have the new version released after testing is complete.

**Comment by rahulrvp** [comment]
dear @ducnnguyen we have released a new version with the fix for this issue. Please update to [v2.0.4](https://github.com/blueshift-labs/Blueshift-iOS-SDK/releases/tag/2.0.4)

I will close this issue now. Feel free to reach out to us if you need any help.
