### ISSUE TITLE
Conflict name with SDWebImage

### ISSUE THREAD

**Issue by ducnnguyen** [blueshift-labs/Blueshift-iOS-SDK#93]
You're using same file name with SDWebImage. 'UIColor+HexString.h'
So we have error when build debug
`'UIColor+HexString.h' file not found`

**Comment by rahulrvp** [comment]
@ducnnguyen Thanks for bringing this to our attention. We will take a look at this.
Meantime, could you please go ahead and open a support ticket and share the following info?
- Screenshot or log of the complete error that you see while debugging
- Blueshift iOS SDK version in use

Rahul Raveendran

**Comment by ducnnguyen** [comment]
I'll create pull request for you

**Comment by rahulrvp** [comment]
Hey @ducnnguyen 
To assist you better, we request you to follow these steps whenever you face an issue with the Blueshift Mobile SDKs.
1. Gather the details like crash log/screenshot, Blueshift iOS SDK version, Campaign details, Template details (if any) etc
2. Raise a support ticket by sending email to support@blueshift.com with all the details collected

Please feel free to ask us if you need more clarification.

Thanks,
Rahul Raveendran

**Comment by ducnnguyen** [comment]
Hey @rahulrvp 
Our project is using both of BlueShift-iOS-SDK and SDWebImage

Our podfile is
>pod 'BlueShift-iOS-SDK', '2.0.1'
pod 'SDWebImage',           '5.3.1'

When i build project, i've got error message is `'UIColor+HexString.h' file not found`

No need any screenshot, crashlog,... you will face off this problem when using with same podfile like me

**Comment by rahulrvp** [comment]
dear @ducnnguyen our engineers have a fix ready for this issue. Will keep you posted.

**Comment by rahulrvp** [comment]
hey @ducnnguyen we have released [v2.0.3](https://github.com/blueshift-labs/Blueshift-iOS-SDK/releases/tag/2.0.3) with a fix for this issue. Please update and let us know the feedback. I will close this issue now. Feel free to open if you have any queries here.
