### ISSUE TITLE
 'BlueShiftNotificationConstants.h' file not found

### ISSUE THREAD

**Issue by ducnnguyen** [blueshift-labs/Blueshift-iOS-SDK#94]
We used BlueShift SDK version 2.0.1
>/Users/ducnguyen/WORKS/BlueShift-iOS-SDK/BlueShift-iOS-SDK/InApps/InAppNotificationEntity.m:9:9: fatal error: 'BlueShiftNotificationConstants.h' file not found
#import "BlueShiftNotificationConstants.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by rahulrvp** [comment]
Thanks for reporting.
Please send us an email at support@blueshift.com with the details. We will look into this.

**Comment by rahulrvp** [comment]
dear @ducnnguyen can we get on a call tomorrow for a live debugging session to resolve this & issue #92 faster? Please let us know a best time that works for you. I'll get an update from our engineers and setup the call.

**Comment by ducnnguyen** [comment]
Dear @rahulrvp, i don't have free time to setup any call. I created a pull request for you here to fix all issues which i reported https://github.com/blueshift-labs/Blueshift-iOS-SDK/pull/96
Please take a look. Thank in advance.

**Comment by rahulrvp** [comment]
Dear @ducnnguyen Looking at the local path mentioned above, we suspect this as an integration issue.
Could you please confirm if you are using CocoaPods to pull the SDK or are you still working with the forked copy?
We strongly recommend to have a short call to resolve this faster.

**Comment by ducnnguyen** [comment]
> Dear @ducnnguyen Looking at the local path mentioned above, we suspect this as an integration issue.
> Could you please confirm if you are using CocoaPods to pull the SDK or are you still working with the forked copy?
> We strongly recommend to have a short call to resolve this faster.

I confirm that i am using CocoaPods to pull your SDK.
I think you should provide example project which include your integration.
We had a call but sorry for my bad English, we can't hear and understand what you say so i think short call will not resolve this faster.

**Comment by rahulrvp** [comment]
dear @ducnnguyen, thanks for confirming the CocoaPod usage.
We have a sample app which you can use to validate your integration. You can find it [here](https://github.com/blueshift-labs/Blueshift-iOS-SampleApp). Latest code can be found in the `development_mainline` branch. Please take a look and feel free to reach out if you need any clarifications or help.

**Comment by rahulrvp** [comment]
dear @ducnnguyen please let us know if the issues #94 & #92 are resolved by fixing the integration steps. We are awaiting your response to release the fix for other two issues.

**Comment by ducnnguyen** [comment]
I see that nothing was changed from your side @rahulrvp ??
Currently, I'm using podfile with your SDK

Main app
>pod 'BlueShift-iOS-SDK', '2.0.1'

Extension app
>pod 'BlueShift-iOS-Extension-SDK','2.0.1'

Is there any problem with our integration step?

**Comment by rahulrvp** [comment]
dear @ducnnguyen we haven't released the SDK with the fixes for #95 & #93 yet. We wanted to see if cross checking with the sample app helped you resolve #94 & #92 before making a new release. Could you please let us know if those two issues were resolved?

**Comment by rahulrvp** [comment]
The latest stable version is [v2.0.2](https://github.com/blueshift-labs/Blueshift-iOS-SDK/releases/tag/2.0.2)

**Comment by rahulrvp** [comment]
hey @ducnnguyen we have released [v2.0.3](https://github.com/blueshift-labs/Blueshift-iOS-SDK/releases/tag/2.0.3) with a fix for this issue. Please update and let us know the feedback. I will close this issue now. Feel free to open if you have any queries here.
