### ISSUE TITLE
You're copying iCarousel from https://github.com/nicklockwood/iCarousel

### ISSUE THREAD

**Issue by ducnnguyen** [blueshift-labs/Blueshift-iOS-SDK#95]
You should change podspec file to
s.dependency 'iCarousel'
or change file name.
We have some problem on our project because of we used both your SDK and `iCarousel`

**Comment by rahulrvp** [comment]
Thanks for reporting.
Please send us an email at support@blueshift.com with the details. We will look into this.

**Comment by rahulrvp** [comment]
dear @ducnnguyen we have the fix ready for this as well. Will be rolling out with our next release. Will keep you posted.

**Comment by rahulrvp** [comment]
hey @ducnnguyen we have released [v2.0.3](https://github.com/blueshift-labs/Blueshift-iOS-SDK/releases/tag/2.0.3) with a fix for this issue. Please update and let us know the feedback. I will close this issue now. Feel free to open if you have any queries here.
