### ISSUE TITLE
Illegal attempt to save to a file that was never opened. "This NSPersistentStoreCoordinator has no persistent stores (unknown)

### ISSUE THREAD

**Issue by ff-adrian-obando** [blueshift-labs/Blueshift-iOS-SDK#97]
Hello, I'm currently writing a bridge to react native, I created a class with the following code:
#import "RNBlueshift.h"

@implementation RNBlueshift

RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(userLogin:(NSString *)email customerId:(NSString *)customerId)
{
  
  NSDictionary *details = @{
                              @"email":email,
                              @"customer_id":customerId,
  };
  
  [[BlueShiftUserInfo sharedInstance] setEmail:email];
  [[BlueShiftUserInfo sharedInstance] setRetailerCustomerID:customerId];

  [[BlueShiftUserInfo sharedInstance] save];
   

  [[BlueShift sharedInstance] identifyUserWithDetails:details canBatchThisEvent:YES];

 
}

@end

Everything is working fine until It tries to identify the user, the app completely crashed with the following error: `[error] error: Illegal attempt to save to a file that was never opened. "This NSPersistentStoreCoordinator has no persistent stores (unknown).  It cannot perform a save operation.". No last error recorded.`

Everything it's been configured according to the documentation, any ideas what could be?

**Comment by aswani521** [comment]
Hey @ff-adrian-obando, In order to better assist you, can you please file a ticket with our customer success.

**Comment by ff-adrian-obando** [comment]
Sure, @aswani521  already submitted, thanks for the help

**Comment by rahulrvp** [comment]
Status: Resolved the integration issues over a call.
